<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <ApplicationIcon>Resources\DNFE_modern.ico</ApplicationIcon>
    <AssemblyName>DDNet ForeEdit</AssemblyName>
    <AssemblyTitle>DDNet ForeEdit</AssemblyTitle>
    <RootNamespace>FontEditor</RootNamespace>
    <Version>2602.0828.34</Version>
    <Authors>ReGoMark</Authors>
    <Company>Bilibili @ReGoMark</Company>
    <Product>DDNet ForeEdit</Product>
    <Copyright>Copyright © 2026 ReGoMark</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dialogs\dated\**" />
    <Compile Remove="Modules\dated\**" />
    <Compile Remove="Resources\dated\**" />
    <EmbeddedResource Remove="Dialogs\dated\**" />
    <EmbeddedResource Remove="Modules\dated\**" />
    <EmbeddedResource Remove="Resources\dated\**" />
    <None Remove="Dialogs\dated\**" />
    <None Remove="Modules\dated\**" />
    <None Remove="Resources\dated\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\DNFE_modern.ico" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="data\SarasaMonoSlabSC-Regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\standard\DejaVuSans.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\standard\Font_Awesome_6_Free-Solid-900.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\standard\GlowSansJ-Compressed-Book.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\standard\index.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\standard\SourceHanSans.ttc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\updates.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Settings.settings">
      <CustomToolNamespace>My</CustomToolNamespace>
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="data\" />
  </ItemGroup>

</Project>